// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsvDR1yXusioL5I7ltV7RtztYh-40lPCI',
    appId: '1:740863650019:web:8071fc1d24c2378015bdd6',
    messagingSenderId: '740863650019',
    projectId: 'weconnect-6ae00',
    authDomain: 'weconnect-6ae00.firebaseapp.com',
    storageBucket: 'weconnect-6ae00.appspot.com',
    measurementId: 'G-EZ7Q63CF2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD60smppAOGfS7VIuRfPhng3LBPj78fOto',
    appId: '1:740863650019:android:7620eed6f75cda4e15bdd6',
    messagingSenderId: '740863650019',
    projectId: 'weconnect-6ae00',
    storageBucket: 'weconnect-6ae00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDacpYeWTOIsfq7DApvzrI5O2byfrvpMa0',
    appId: '1:740863650019:ios:d31ae10487c9acb915bdd6',
    messagingSenderId: '740863650019',
    projectId: 'weconnect-6ae00',
    storageBucket: 'weconnect-6ae00.appspot.com',
    iosClientId: '740863650019-u4b70rbafd5gubv9naiq2ngu5no398ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.weconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDacpYeWTOIsfq7DApvzrI5O2byfrvpMa0',
    appId: '1:740863650019:ios:d31ae10487c9acb915bdd6',
    messagingSenderId: '740863650019',
    projectId: 'weconnect-6ae00',
    storageBucket: 'weconnect-6ae00.appspot.com',
    iosClientId: '740863650019-u4b70rbafd5gubv9naiq2ngu5no398ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.weconnect',
  );
}
